module.exports = {
  // Lista de todas as rotas para pré-renderizar (SEM barra final)
  include: [
    "/",
    "/criar-lista",
    "/lista-de-compras",
    "/lista-de-compras-completa",
    "/lista-supermercado",
    "/lista-duas-pessoas",
    "/lista-mensal",
    "/lista-solteiro",
    "/lista-saudavel",
    "/lista-de-material-escolar",
    "/lista-de-material-escolar-2026",
    "/lista-de-material-escolar-educacao-infantil",
    "/lista-de-material-escolar-1-ano",
    "/lista-de-material-escolar-2-ano",
    "/lista-de-material-escolar-3-ano",
    "/lista-de-material-escolar-4-ano",
    "/lista-de-material-escolar-5-ano",
    "/lista-de-material-escolar-6-ano",
    "/lista-de-material-escolar-7-ano",
    "/lista-de-material-escolar-8-ano",
    "/lista-de-material-escolar-9-ano",
    "/lista-de-material-escolar-ensino-medio",
    "/lista-de-casa-nova",
    "/lista-de-casa-nova-completa",
    "/lista-de-casa-nova-cozinha",
    "/lista-de-casa-nova-quarto",
    "/lista-de-casa-nova-sala",
    "/lista-de-casa-nova-banheiro",
    "/lista-de-casa-nova-limpeza",
    "/lista-de-casa-nova-area-de-servico",
    "/lista-de-casa-nova-economica",
    "/lista-de-casamento",
    "/checklist-de-casamento-completo",
    "/lista-de-casamento-tradicional",
    "/lista-de-casamento-12-meses-antes",
    "/lista-de-casamento-6-meses-antes",
    "/lista-de-casamento-3-meses-antes",
    "/lista-de-fornecedores-casamento",
    "/lista-de-convidados-casamento",
    "/checklist-lua-de-mel",
    "/blog",
    "/blog/dicas-economizar-supermercado",
    "/blog/casa-inteligente-guia-2026",
    "/blog/energia-solar-residencial-2026",
    "/como-usar",
    "/baixar-em-pdf",
    "/imprimir-listas",
    "/contato",
    "/sitemap",
    "/glossario",
    "/glossario/o-que-e-checklist-de-casa-nova",
    "/glossario/o-que-e-enxoval-de-casa",
    "/glossario/o-que-e-kit-cozinha-basica",
    "/glossario/o-que-e-lista-de-mudanca",
    "/glossario/o-que-e-lista-de-compras",
    "/glossario/o-que-e-lista-de-supermercado",
    "/glossario/o-que-e-lista-mensal-de-compras",
    "/glossario/o-que-e-lista-de-compras-saudavel",
    "/glossario/o-que-e-planejamento-de-cardapio",
    "/glossario/o-que-e-checklist-de-casamento",
    "/glossario/o-que-e-lista-de-convidados",
    "/glossario/o-que-e-lista-de-fornecedores",
    "/glossario/o-que-e-checklist-lua-de-mel",
    "/glossario/o-que-e-lista-de-material-escolar",
    "/glossario/o-que-e-material-escolar-2026",
    "/glossario/o-que-e-kit-alfabetizacao",
    "/glossario/o-que-e-organizacao-de-mochila",
    "/glossario/o-que-e-planner-semanal",
    "/glossario/o-que-e-to-do-list",
    "/glossario/o-que-e-checklist",
    "/glossario/o-que-e-gestao-do-tempo",
    "/glossario/o-que-e-orcamento-domestico",
    "/politica-de-privacidade",
    "/politica-de-cookies",
    "/termos-de-uso",
  ],
  // Configurações de pré-renderização
  puppeteerArgs: ["--no-sandbox", "--disable-setuid-sandbox"],
  puppeteerExecutablePath: undefined,
  // Aguardar renderização completa
  waitUntil: "networkidle0",
  // Injetar dados de rota
  inlineCss: true,
  // Manter estrutura de diretórios
  removeBlobs: true,
  fixInsertRule: true,
  // Não incluir scripts desnecessários
  skipThirdPartyRequests: false,
  // Configuração de viewport
  viewport: {
    width: 1440,
    height: 900,
  },
};
